config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do 
  	resources :comments
  end
  root  "products#index"

  get '/admin' => "admins#index"
  resources :admins
  get '/search' => "products#search"
  get '/merge' => "products#merge"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	def self.get_all_categories
		Category.all
	end
	
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  def self.create(e,user_id)
    logger.info(e)
  	comment = Comment.new
  	comment.content = e[:q]
  	comment.product_id = e[:product_id]
  	comment.user_id = user_id
  	
  	comment.save

  end
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :comments
	belongs_to :user
	belongs_to :category
	

  has_attached_file :product_img, styles: { product_index: "300x300>", product_show: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :product_img, content_type: /\Aimage\/.*\z/



	def self.get_active_product
	 Product.where(status: 'Activate') 
	end
	
	def self.create(e, cat, user_id)
		prod = Product.new
		prod.name = e[:name]
		prod.description = e[:description]
		prod.cost_of_product = e[:cost_of_product]
		prod.no_of_stock = e[:no_of_stock]
		prod.status = e[:status]
		prod.feature = e[:feature]
		prod.category_id = cat 
		prod.user_id = user_id
		
		prod.save
	end


	def self.update(id, e, cat, user_id)
		prod = Product.find(id)

		prod.name = e[:name]
		prod.description = e[:description]
		prod.cost_of_product = e[:cost_of_product]
		prod.no_of_stock = e[:no_of_stock]
		prod.status = e[:status]
		prod.feature = e[:feature]
		prod.category_id = cat
		prod.user_id = user_id
		prod.save
	end
end

app/models/user.rb
class User < ApplicationRecord
 has_many :products
 has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :find_product, only: [:show,:edit,:update,:destroy]
	def index
		@products = Product.all.paginate(page: params[:page], per_page: 10)
	end

	def new
		if user_signed_in?
		@product = current_user.products.build
		else redirect_to  new_user_registration_path
		end
	end

	def create
		@product = current_user.products.build(product_params)
		if @product.save
			redirect_to products_path
		else render 'new'
		end
	end


	


	private
	def product_params
		params.require(:product).permit(:name,:description,:cost_of_product,:no_of_stock,:status,:feature)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_product

	def create
		
		user_id = current_user.id

		@comment = Comment.create(product_params,user_id)
		

		if @comment.present?
			redirect_to "/products/#{params[:product_id]}"
		else render 'new'
		end
	end


	private
	
	def product_params
		params.permit(:q,:product_id)
	end

	def find_product
		@product = Product.find(params[:product_id])
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	layout 'application', except: [:search,:merge]
	before_action :find_product, only: [:show,:edit,:update,:destroy]
	
	def index
		@products = Product.get_active_product.paginate(page: params[:page], per_page: 8)
	end

	def new
		if user_signed_in?
		@product = current_user.products.build
		@categories = Category.get_all_categories
		else redirect_to  new_user_registration_path
		end
	end

	def create
		
		category = params[:product][:category]
		user_id = current_user.id

		@product = Product.create(product_params, category, user_id)
		
		if @product.present?
			redirect_to products_path
		else
			redirect_to 'new'
		end

	end

	def show
		@comments = @product.comments
		
	end

	def edit
		@categories = Category.get_all_categories
	end

	def update

		category = params[:product][:category]

		user_id = current_user.id
		id = params[:id]
		

		@product = Product.update(id, product_params,category,user_id)
		if @product.present?
			redirect_to products_path
		else 
			redirect_to edit_product_path
		end
	end
	
	def destroy
		@product.destroy
		redirect_to root_path
	end

	def search
		if params[:q] == "1" 
			params[:q] = "Activate"

		elsif  params[:q] == "2"
			params[:q] = "Deactivate"
		else
			
		end

		query = params[:q].present? ? params[:q] : 1 
		@products = Product.where(status: query).paginate(page: params[:page], per_page: 8) 
		render 'index', layout: false
	end

	def merge
		if 
			params[:q] == "1"
			params[:q] = 1

		elsif 
			params[:q] == "2"
			params[:q] = 2

		elsif params[:q] == "3"
			params[:q] = 3

		else 
			params[:q] = [1,2,3]
		end
		query = params[:q].present? ? params[:q] : 1
		
		@products = Product.where(category_id: query).paginate(page: params[:page], per_page: 8)
		logger.info(@products.size)
		render 'index', layout: false		
	end

	private
	def product_params
		params.require(:product).permit(:name,:description,:cost_of_product,:no_of_stock,:status,:feature,:category,:product_img)
	end
	def find_product
		@product = Product.find(params[:id])
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/_form.html.erb
<%= simple_form_for @product do |f| %>
  
  
  <select name="product[category]">
  	<option value="">Select a category</option>
  	<% @categories.each do |category|%>
  	 <option value="<%=category.id%>"><%=category.name%></option>

  	<% end %>
  </select>
  
  <%= f.file_field :product_img%>
  <%= f.input :name, label: 'Product Name' %>
  <%= f.input :description, label: 'Description' %>
  <%= f.input :feature %>
  <%= f.input :cost_of_product %>
  <%= f.input :no_of_stock %>
  <%= f.input :status, :collection => ["Activate","Deactivate"], :as => :radio_buttons, :checked =>"Activate",:item_wrapper_class => 'inline',:label => "Status" %>
  <%= f.button :submit %>
<% end %>

app/views/admins/edit.html.erb
<h1>Edit Your Product</h1>
<%= render 'form'%>

app/views/admins/index.html.erb
<%= will_paginate @products %>




<div class="row">
	<%= @products.each do |product|%>
		<% if user_signed_in?%>
			<% if product.user_id == current_user.id%>
			<div class="col-md-3">
				<a href="/products/<%= product.id%>">
					<%= image_tag product.product_img.url(:product_index) , class:"book"%>
				</a>
			</div>
			<% end -%>	
		<% end %>
	<% end %>
</div>
<br>

<%= link_to "Add Product",  new_product_path,class:"btn btn-primary"%>

<%= will_paginate @products %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" >    
  <div style="background-color: #232F3E" class="container-fluid ">
    
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" style="color: white">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <h2 class="brand brand-name navbar-left">
           <a style="color: white"  href="<%= root_path%>"><img class="img-responsive2"       
           src="/assets/DigitalPondlogo2.png">eShop</a>
       </h2>
    </div>

   
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
       <%= link_to "Admin", admin_path,class: "navbar-brand",style:"color: white"%>
        <% if !user_signed_in?%>
        <li><%= link_to "Sign Up", new_user_registration_path ,style:"color: white",class: "navbar-brand"%></li>
        <% else %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :Delete ,style:"color: white",class: "navbar-brand"%></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-brand" ">
      <% if user_signed_in?%>
        
        <select id="stat" name="status">
          <option value="">Select Active/Deactive</option>
          <option id="activ" value="1">Activate</option>
          <option value="2">DeActivate</option>
        </select>
  
      <% end %>

        <select id="cate" name="category">
          <option value="">Select Category</option>
          <%= Category.all.each do |category|%>
          <option value="<%=category.id%>"><%= category.name%></option>
          <% end %>
        </select>


      </ul>
    </div>
  </div>
</nav>

<script>
  $(document).ready(function(){
    
    $('#stat').change(function(){
      
      var SelectedValue = parseInt(jQuery(this).val());
  
      $.get("/search?q="+SelectedValue, function(data, status){
        $("#print").html(data);
      });
    });
  });
</script>




<script>
  
  $(document).ready( function(){
    
    $('#cate').change(function(){

      var SelectedOption = parseInt(jQuery(this).val());
      
      $.get("/merge?q="+SelectedOption, function(data, status){
        $("#print").html(data);

      });
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoListApp</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  	<%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/products/_search.html.erb
<%= @products.each do |product|%>
	<div class="col-md-3">
		<a href="/products/<%=product.id%>">
		<%= image_tag product.product_img.url(:product_index) ,class:"product"%>
		</a>
	</div>	
 	<% end %>
	

app/views/products/edit.html.erb
<h1>Edit Your Product</h1>
<%= render 'admins/form'%>

app/views/products/index.html.erb
<%= will_paginate @products %>

<div id="print" class="row">
	<%= render 'search'%>
</div>
	

app/views/products/new.html.erb
<h2>Add New Product</h2>
<%= render 'admins/form'%>

app/views/products/show.html.erb
<div class="row">
	
	<div class="col-md-5">
		<%= image_tag @product.product_img.url(:product_show), class:"product_show"%>
	</div>
	<div class="col-md-7">
		<blockquote>
			<h2><%= @product.name%></h2>
			<h3>Category: <%= @product.category.name%></h3>
		<h3>Description <small><%= @product.description%></small></h3>
		<h3>Feature <small><%= @product.feature%></small></h3>
		<h3>Cost Rs: <%= @product.cost_of_product%></h3>
		<h3>No.of Stock: <%= @product.no_of_stock%></h3>
		<% if user_signed_in?%>

		<% if @product.user_id == current_user.id%>
		<%= link_to "Back", root_path, class:"btn btn-info"%>
		<%= link_to "Edit Product", edit_product_path, class:"btn btn-success"%>

		<%= link_to "Destroy", product_path(@product),class:"btn btn-danger", method: :DELETE, data: {confirm: "Are you sure?" }%>

		<% else%>
		<%= link_to "Back", root_path, class:"btn btn-info"%>

		<% end %>
		<% else%>
		<%= link_to "Back", root_path, class:"btn btn-info"%>

		<% end %>
		</blockquote>
		<h3>Comments</h3>
			<% @comments.each do |comment|%>
				<h4><%=comment.user.email%><br></h4>
				<%= comment.content%><hr>

			<% end %>

		<% if user_signed_in?%>
		
			<%= form_tag("/products/" + @product.id.to_s + "/comments", method: "post") do %> 
			 <%= label_tag(:q, "Comment Here:") %><br> 
			 <%= text_field_tag(:q) %> 
			 <%= submit_tag("Create Comment") %> 
		 <% end %> 
		
		<% end -%>

	</div>
</div>